theme : minima
title: Sai Prashanthi's Portfolio
author: Sai Prashanthi
email: mpprasanthi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am currently pursuing my Full Stack Developer from GenerationUSA.My strong points include problem-solving, persistence, communication skills, comfortable to work as an individual or as part of a team. 
  I am currently looking to progress my career by taking on a Junior Full Stack Engineer position.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
